return {}
-- local function env(name)
--   local value = vim.env[name]
--   return value ~= '' and value or nil
-- end
--
-- local openai_headers = {}
-- local openai_org = env 'OPENAI_ORG_ID' or env 'OPENAI_ORGANIZATION'
-- local openai_project = env 'OPENAI_PROJECT_ID' or env 'OPENAI_PROJECT'
--
-- if openai_org then
--   openai_headers['OpenAI-Organization'] = openai_org
-- end
--
-- if openai_project then
--   openai_headers['OpenAI-Project'] = openai_project
-- end
--
-- return {
--   'yetone/avante.nvim',
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   -- ⚠️ must add this setting! ! !
--   build = vim.fn.has 'win32' ~= 0 and 'powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false' or 'make',
--   event = 'VeryLazy',
--   version = false, -- Never set this value to "*"! Never!
--   ---@module 'avante'
--   ---@type avante.Config
--   opts = {
--     instructions_file = 'avante.md',
--     provider = 'openai',
--     behaviour = {
--       auto_suggestions = false,
--       auto_apply_diff_after_generation = false,
--       auto_approve_tool_permissions = false,
--     },
--     prompt_logger = {
--       enabled = false,
--     },
--     providers = {
--       openai = {
--         endpoint = env 'AVANTE_OPENAI_ENDPOINT' or env 'OPENAI_BASE_URL' or env 'OPENAI_API_BASE' or 'https://api.openai.com/v1',
--         model = env 'AVANTE_OPENAI_MODEL' or env 'OPENAI_MODEL' or 'gpt-4o',
--         api_key_name = 'OPENAI_API_KEY',
--         timeout = tonumber(env 'AVANTE_OPENAI_TIMEOUT_MS') or 60000,
--         context_window = 128000,
--         extra_headers = next(openai_headers) ~= nil and openai_headers or nil,
--         use_response_api = function(opts)
--           local model = opts and opts.model
--           return type(model) == 'string' and model:match 'gpt%-5%-codex' ~= nil
--         end,
--         extra_request_body = {
--           temperature = 0.2,
--           max_completion_tokens = 16384,
--         },
--       },
--       claude = {
--         endpoint = 'https://api.anthropic.com',
--         model = 'claude-sonnet-4-20250514',
--         timeout = 30000, -- Timeout in milliseconds
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 20480,
--         },
--       },
--       moonshot = {
--         endpoint = 'https://api.moonshot.ai/v1',
--         model = 'kimi-k2-0711-preview',
--         timeout = 30000, -- Timeout in milliseconds
--         extra_request_body = {
--           temperature = 0.75,
--           max_tokens = 32768,
--         },
--       },
--     },
--   },
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'MunifTanjim/nui.nvim',
--     --- The below dependencies are optional,
--     'nvim-mini/mini.pick', -- for file_selector provider mini.pick
--     'nvim-telescope/telescope.nvim', -- for file_selector provider telescope
--     'hrsh7th/nvim-cmp', -- autocompletion for avante commands and mentions
--     'ibhagwan/fzf-lua', -- for file_selector provider fzf
--     'stevearc/dressing.nvim', -- for input provider dressing
--     'folke/snacks.nvim', -- for input provider snacks
--     'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
--     'zbirenbaum/copilot.lua', -- for providers='copilot'
--     {
--       -- support for image pasting
--       'HakonHarnes/img-clip.nvim',
--       event = 'VeryLazy',
--       opts = {
--         -- recommended settings
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           -- required for Windows users
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { 'markdown', 'Avante' },
--       },
--       ft = { 'markdown', 'Avante' },
--     },
--   },
-- }
